### ISSUE TITLE
MES fix for collector horn

### ISSUE THREAD

**Issue by SkylerPIlot** [SkylerPIlot/Ba-Minigame#1]
I have received reports of the new update breaking the current MES for the "swap collector horn" option feel free to look into or fix, i'll probably get to it sometime next week if nobody else picks it up.

**Comment by equirs** [comment]
A workaround for this: use the standard MES left click swapper to make defensive the left click option. Then all the calls are adjacent to one another. Controlled goes to the bottom, though, so prepare to call incorrectly while adjusting

**Comment by SkylerPIlot** [comment]
If anybody wants to test I believe the fix is to insert 
```
if (entry1.isItemOp() && entry1.getType() == MenuAction.CC_OP_LOW_PRIORITY)
		{
			entry1.setType(MenuAction.CC_OP);
		}
		if (entry2.isItemOp() && entry2.getType() == MenuAction.CC_OP_LOW_PRIORITY)
		{
			entry2.setType(MenuAction.CC_OP);
		}
```
on this [line](https://github.com/SkylerPIlot/Ba-Minigame/blob/67e26acf276b60881871321eef41ce81fbe7fd48/src/main/java/begosrs/barbarianassault/menuentryswapper/MenuEntrySwapper.java#L175)

**Comment by ransty** [comment]
I don't think it's that simple of a fix, due to the way beg has implemented the entryswapper for this plugin. Looks like we need to subscribe to a MenuOption event, like `onMenuOptionClicked` to actually extract it properly. At the moment it looks like beg just implemented a brute force way. I might be totally wrong, but seem to be unable to check `isItemOp()` because it's an interface and the MenuEntry doesn't actually implement it.

I am probably talkin out of my ass, but I can't seem to hit the `isItemOp()` with this code block on that line.

**Comment by ransty** [comment]
Works, I was talkin out my ass.

**Comment by ransty** [comment]
Fixed
